version: '3.7'

services:
  php:
    image: wutti/php:fpm-alpine
    build: .
    container_name: phpfpm_oci8
    restart: always
    volumes:
      - ./www/:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./www/:/var/www/html
    ports:
      - 80:80
